# A basic TCP load-balancer for scaling out Puppet Servers.

[logging]
  level = "debug"
  output = "stdout"

[api]
  enabled = true
  bind = ":8888"
  cors = false                    # cross-origin resource sharing

[servers.puppet]
  bind = "0.0.0.0:8140"
  balance = "roundrobin"          #  (optional [weight]) "weight" | "leastconn" | "roundrobin" | "iphash" | "leastbandwidth"
  max_connections = 5
  client_idle_timeout = "10m"
  backend_idle_timeout = "10m"
  backend_connection_timeout = "5s"

[servers.puppet.discovery]
  kind = "docker"
  docker_endpoint = "unix:///var/run/docker.sock" # (required) Endpoint to docker API
  docker_container_label = "puppetserver=true"    # (optional) Label to filter containers
  docker_container_private_port = 8140            # (required) Private port of container to use
  interval = "5s"
